### ISSUE TITLE
TypeError: Cannot read property 'temp' of undefined

### ISSUE THREAD

**Issue by mwittig** [bredele/meteo#1]
Unfortunately, meteo does not work for me. I am using node v4.4.0

```
>meteo -l 'paris' -u 'f'
C:\Users\marcus\AppData\Roaming\nvm\v4.4.0\node_modules\meteo\bin\meteo:64
                        temp = weather.main.temp;
                                           ^

TypeError: Cannot read property 'temp' of undefined
    at C:\Users\marcus\AppData\Roaming\nvm\v4.4.0\node_modules\meteo\bin\meteo:64:23
    at Request.callback (C:\Users\marcus\AppData\Roaming\nvm\v4.4.0\node_modules\meteo\node_modules\superagent\lib\node\index.js:656:3)
    at Request.<anonymous> (C:\Users\marcus\AppData\Roaming\nvm\v4.4.0\node_modules\meteo\node_modules\superagent\lib\node\index.js:131:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\marcus\AppData\Roaming\nvm\v4.4.0\node_modules\meteo\node_modules\superagent\lib\node\index.js:802:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:442:9)
```

**Comment by bredele** [comment]
hey @mwittig I just noticed openweathermap is not that open anymore and we will need an API key in order to use their API. Would you be interested into implementing that?

**Comment by mwittig** [comment]
Thanks for the swift response.

> ...  need an API key in order to use their API. Would you be interested into implementing that?

Yes, I am happy to do this. I have done this before as part of https://github.com/josecastroleon/pimatic-openweather/. I am not sure, however, what is the best of poviding the api key to an globally installed package

**Comment by bredele** [comment]
@mwittig right :p I don't think it would be a good idea. The key could be an option in the CLI but I find that annoying to set it up the first time. Do you know if there is any legit weather API without need of API keys?

**Comment by mwittig** [comment]
Just found the following: https://www.metaweather.com/api/ - aggregates weather data from various sources, location search required to obtain the woeid for the location is not very good (my hometown wasn't found eventhough it is important meteorology site

Presumably most weather sites requires users to obtain API key as their service have been abused or overused.

What may work: Provide the api-key via command line when run for the first time (as root / Administrator). Then the API key is written to the package.json file.

**Comment by bredele** [comment]
@mwittig sure I will take a look when I have time :) thanks
